- name: add users
  hosts: localhost
  tasks:
  - name: Include members
    include_vars:
      file: vars/members.yml
      name: members
  - name: auth0_ext
    auth0_ext:
      domain_main: 'https://dev-prom.auth0.com'
      domain_ext: 'https://dev-prom.us8.webtask.io/adf6e2f2b84784b57522e3b19dfc9201/api'
      client_id: 'vY2ixUH3W2FVAJ4u9YROelG2UfIzzI91'
      client_secret: '-JnFRoJ22gi5vitgvMW21MdZbRssFYjb7USbVMtxdeWeX8jy_08b8zUTrxiRKWpN'
      members: "{{ item.member }}"
      groups: "{{ item.group }}"
      state: present
    with_items:
      - "{{ members.members }}"

- name: delete users
  hosts: localhost
  tasks:
  - name: Include members
    include_vars:
      file: vars/members_delete.yml
      name: members
  - name: auth0_ext
    auth0_ext:
      domain_main: 'https://dev-prom.auth0.com'
      domain_ext: 'https://dev-prom.us8.webtask.io/adf6e2f2b84784b57522e3b19dfc9201/api'
      client_id: 'vY2ixUH3W2FVAJ4u9YROelG2UfIzzI91'
      client_secret: '-JnFRoJ22gi5vitgvMW21MdZbRssFYjb7USbVMtxdeWeX8jy_08b8zUTrxiRKWpN'
      members: "{{ item.member }}"
      groups: "{{ item.group }}"
      state: absent
    with_items:
      - "{{ members.members }}"

  